# ACLSwitch ACL rule configuration file
#
# Define ACL rules
#
# Configuration items are loaded in the following order:
#    - Policy Domains
#    - ACL rules
#    - Policy Domain switch assignments
#
# Exmaple below:
#
#a cl_rules:
#   - "ip_src": "10.0.0.1"
#     "ip_dst": "10.0.0.2"
#     "tp_proto": "*"
#     "port_src": "*"
#     "port_dst": "*"
#     "policy": "default"
#     "action": "drop"
#   - "ip_src": "10.0.0.1"
#     "ip_dst": "10.0.0.3"
#     "tp_proto": "tcp"
#     "port_src": "*"
#     "port_dst": "*"
#     "policy": "test1"
#     "action": "drop"
#   - "ip_src": "10.0.0.1"
#     "ip_dst": "10.0.0.3"
#     "tp_proto": "*"
#     "port_src": "*"
#     "port_dst": "*"
#     "policy": "default"
#     "action": "allow"
#   - "ip_src": "10.0.0.3"
#     "ip_dst": "10.0.0.1"
#     "tp_proto": "*"
#     "port_src": "*"
#     "port_dst": "*"
#     "policy": "default"
#     "action": "allow"
#   - "ip_src": "10.0.0.1"
#     "ip_dst": "10.0.0.2"
#     "tp_proto": "tcp"
#     "port_src": "*"
#     "port_dst": "80"
#     "policy": "default"
#     "action": "drop"
#     "time_enforce": ["12:00",60]
#   - "ip_src": "10.0.0.2"
#     "ip_dst": "10.0.0.1"
#     "tp_proto": "tcp"
#     "port_src": "*"
#     "port_dst": "22"
#     "policy": "default"
#     "action": "drop"
#     "time_enforce": ["11:00",60]

acl_rules:
  - Null