# ACLSwitch Policy Domain configuration file
#
# Define and assign Policy Domains in this file. Set the values within
# the policy_domains and pd_assignment keys to Null if no values are
# desired.
#
# Configuration items are loaded in the following order:
#    - Policy Domains
#    - ACL rules
#    - Policy Domain switch assignments
#
# Example below:
#
# policy_domains:
#   - "example1"
#   - "example2"
#
# pd_assignments:
#   - switch_id: 1
#     policy: "example1"
#   - switch_id: 2
#     policy: "example2"
#
policy_domains:
  - Null

pd_assignments:
  - Null